### ISSUE TITLE
quad head status

### ISSUE THREAD

**Issue by jbolene** [PrintM3D/Promega#14]
the kickstarter surveys were supposed to go out this week
what is the status?
when are they shipping?
are they faster than the compound?
where are the mounts?

**Comment by michaelarmani** [comment]
surveys are going out as we speak.
Mounts are being internally developed / under testing currently
they are shipping over the course of the next 1-2 weeks.
They seem to be able to extrude quite a bit faster than compound, probably owing to a variety of factors.  45 mm/s  0.2mm layers 0.4mm width = 3.6mm^3/s for PLA is where we were on prototype versions which were set very conservatively.   We see potential for up to 12mm^3/s with PETG (About 54 grams an hour )

**Comment by jbolene** [comment]
I am backer #1 group #1, seems if surveys were going out that I would have one

**Comment by sohjsolwin** [comment]
@jbolene are you referring to the crane quad backing on FFL, the QuadFusion print head only backing on FFL, or the QuadFusion backing on Kickstarter?
