### ISSUE TITLE
machine version?

### ISSUE THREAD

**Issue by jbolene** [PrintM3D/Promega#15]
how are we to know which version we have to know where to start looking at the changes needed to bring it up to the current production model?

**Comment by sohjsolwin** [comment]
For the software: It's best to begin by updating to the latest files available on the github when receiving your printer. From there, it's a matter of personally keeping track of what release you updated to. You could place a file on your SD card to keep track of it if you like. 

For the hardware: Having some sort of internal "revision" number for the printers would be beneficial. Something that relates to the combination of the 3D printed parts plus any other modifications that come from M3D and are implemented on the assembly line. 

For improvements that are suggested/made available, but are not implemented in the assembly line, simply indicating such should be sufficient for tracking. having a page in the wiki that lists the "revision" numbers, possibly with a dedicated page per revision that lists and links to each part revision would be helpful.
