### ISSUE TITLE
extruders

### ISSUE THREAD

**Issue by jbolene** [PrintM3D/Promega#16]
https://store.printm3d.com/collections/parts/products/m3d-dual-independent-ktana-extrusion-sub-assembly-m3d0540806?variant=12397458653262

why is this part suggested for the lite machine when it does not have all the parts with it to install it?
it assumes you already have the compound installed and uses parts from it

**Comment by ericl-m3d** [comment]
Hello jbolene,

Please log ONLY issues pertinent to software bugs or operational anomalies (suspected to be software-related).
Any other type of issues logged will be not be addressed and will be deleted.

If you are looking for support, feel free to look through our ever-improving documentation for quick help. 

- [M3D's Official Troubleshooting & Self-Help Guide](https://coda.io/d/M3D-Official-Troubleshooting-Self-Help-Guide_dzE73kMbIAL/Introduction_sucuq#_lulpw)
- [Promega Guides & Instructions](https://promega.printm3d.com/)

Our support ticket is available at https://store.printm3d.com/pages/support.

If you'd like to voice your input on improving our documentation, visit: 
- M3D's Official Troubleshooting & Self-Help Guide [Contribution & Suggestion Page](https://coda.io/d/M3D-Official-Troubleshooting-Self-Help-Guide_dzE73kMbIAL/Coda-Edits-Requests-Form_suKF6#_luq0Y)
- Promega Guides & Instructions [Contribution & Suggestion Page](https://promega.printm3d.com/#contributing)

-M3D Team
