### ISSUE TITLE
missing screws in back heat bed

### ISSUE THREAD

**Issue by jbolene** [PrintM3D/Promega#17]
the back part of the heat bed wobbles if these screws are missing

the back should look like the front

**Comment by michaelarmani** [comment]
The bed is designed without screws in key locations as this pattern optionally reduced bed warp.  The back cover print maintains the dimensions needed while allowing for some thermal expansion.  4 screw holes of 11 won't be populated.

**Comment by jbolene** [comment]
my bed mesh was much better after adding the back screws
the back of the bed was wobbly without them
no problem if you never plan to print to the back to utilize the full bed
