### ISSUE TITLE
needs to be updated 

### ISSUE THREAD

**Issue by jbolene** [PrintM3D/Promega#18]
this is the old wiring harness not the new one

https://promega.printm3d.com/maintenance-guides/changing/changing-extruders

**Comment by sohjsolwin** [comment]
For long term ease of maintenance. I would recommend linking to the "Setting up the wiring harness" page  (https://promega.printm3d.com/electrical-guides/extruder-assembly-wiring#new-extruder-assembly-wiring) for the portion that references the wiring of the exturder. This way, the assembly wiring page can be kept up for the new harnesses and such, and every page that includes a picture of the harness does not also need to be tracked and updated constantly.
