### ISSUE TITLE
Plastic Insert Wear

### ISSUE THREAD

**Issue by tirelessirony** [PrintM3D/Promega#19]
![img_20180830_210922129_hdr](https://user-images.githubusercontent.com/42871660/44920646-7d694b00-ad0e-11e8-8a85-97efeb6c3e7a.jpg)

In trying to track down the cause of extruder gear slipping on PLA prints I started to examine the walle and extruder gears. I had reassembled the K'tana once without the black insert, so I knew that without it 1.75 filament slides forward in the 'feed channel' and isn't pushed effectively by the extruder gear at all. I hypothesized wear on the black insert might account for play developing into skipping.

To test it, I put calipers on the black insert from my K'tana head to check the difference between the unused side and the side which had printed using ABS-R and PLA. here's the results of the thickness. The piece of plastic along the edge (the part that sits in the feed channel) tapers toward the top and is thickest where it butts up against the ptfe tube:
                             Left side (used for ~200hrs)/ Right side (nearly unused entirely)
thinnest part :      2.14mm       /   2.21mm
center             :      2.43mm      /    2.56mm
thickest part :      2.79mm      /    2.93mm 

if you look at the side that has ~200hrs of use, there is a small, shiny, filament sized and shaped groove appearing (see photo). After private discussions with atleast one other user w/ 1000 hrs of use and seeing substantially more wear, I present y'all with the theory wear on the insert could be contributing to direct drive gear skipping that presents as underextrusion. Thanks for your time.

**Comment by J-wMueller** [comment]
Same here, can post pictures of two different inserts with wear.

**Comment by michaelarmani** [comment]
Thanks, we had planned to increase the longevity to about ~10000 hrs using nylon.

**Comment by jbolene** [comment]
why not use carbon petg?  abrasiveness?
when will the new ones be available and will they be shipped to existing customers?

**Comment by tirelessirony** [comment]
Update on Wear. I've added roughly another 100 hours of wear (mostly PLA, a bit of ABS-R) to the Left side exclusively, was swapping nozzles and I wanted to update the measurements:

Left side (used for ~300hrs)/ Right side (nearly unused entirely)
thinnest part : 1.95mm / 2.20mm
center : 2.40mm / 2.51mm
thickest part : 2.85mm / 2.90mm

I fully admit my calipers (or application of them) might be off .01-.05mm off, perhaps based on as little as where they find purchase on the slightly irregular surfaces of the piece, but I'm still seeing a significant difference. As much as a quarter mm of wear from one side vs the other. So 1/7 of the 1.75 filaments diameter is now able to be pushed forward in the feed channel on the left.

Skipping has gotten worse and has now appeared in many of my ABS-R prints (which prior to printing w/ PLA were consistently smooth and free of under-extrusion caused by skipping). 

Here's another photo, from an angle where you can see the wear on the raised portion that sits in the feed channel and the 'backplate' portion of this plastic insert.
![img_20180907_225051921_hdr](https://user-images.githubusercontent.com/42871660/45249600-0248fb80-b2f1-11e8-88a6-bf4e000c8ef2.jpg)

**Comment by Turtle49** [comment]
Same happened to me. I am waiting for a Nylon insert 3D printed by a commercial printing service. Teflon/PTFE may be the best material to use, though can't be printed.
