### ISSUE TITLE
The compound screws do not fit the K'tana hot end.

### ISSUE THREAD

**Issue by hallambaker** [PrintM3D/Promega#20]
I just took my printer apart to swap out the compound end and install a K'tana. The top two screws fit but the middle one  won't fit in the hole. A socket head screw did fit but my machine isn't all Torx screws now.

**Comment by jbolene** [comment]
my ktana came with a middle screw to use

**Comment by ktapper** [comment]
Could we get spec on the bolt.  I am also missing that screw

**Comment by hallambaker** [comment]
I substituted an m4 sockethead which did fit. Not sure how long though.
