### ISSUE TITLE
Not getting any extrusion at all.

### ISSUE THREAD

**Issue by hallambaker** [PrintM3D/Promega#21]
I have leveled my bed to within 1mm. I have set the end stops. I have set the temperature to 200 and loaded PLA. The tube is in the K'tana extruder.

I hit Extrude, 100 mm at 60mm/sec, nothing happens. Nothing happens at any other speed etc. either.

Also, have only one extruder showing, the other is permanently on standby.

**Comment by hallambaker** [comment]
OK, have dispensed with the PTFE tubes and it is now working.

Next problem: getting PLA to stick to the bed.

**Comment by sohjsolwin** [comment]
60mm/s is way too high for most filaments for an open air extrude. You will also quickly run into issue with PLA and not using the PTFE tubes. PLA does not have the necessary lubricants in the material to not burn and stick to the metal. If using the Duet Web Controller, 5-15mm/s is generally the max you want to use through that UI when testing.

**Comment by ericl-m3d** [comment]
Hello hallambaker,

Please log ONLY issues pertinent to software bugs or operational anomalies (suspected to be software-related).
Any other type of issues logged will be not be addressed and will be deleted.

If you are looking for support, feel free to look through our ever-improving documentation for quick help. 

- [M3D's Official Troubleshooting & Self-Help Guide](https://coda.io/d/M3D-Official-Troubleshooting-Self-Help-Guide_dzE73kMbIAL/Introduction_sucuq#_lulpw)
- [Promega Guides & Instructions](https://promega.printm3d.com/)

Our support ticket is available at https://store.printm3d.com/pages/support.

If you'd like to voice your input on improving our documentation, visit: 
- M3D's Official Troubleshooting & Self-Help Guide [Contribution & Suggestion Page](https://coda.io/d/M3D-Official-Troubleshooting-Self-Help-Guide_dzE73kMbIAL/Coda-Edits-Requests-Form_suKF6#_luq0Y)
- Promega Guides & Instructions [Contribution & Suggestion Page](https://promega.printm3d.com/#contributing)

-M3D Team

NOTE: This [sub-section](https://coda.io/d/M3D-Official-Troubleshooting-Self-Help-Guide_dzE73kMbIAL/Promega-Troubleshooting_suSw-#_lurJI) (within the Troubleshooting & Self-Help Guide) should start you off in the right direction, before submitting a support ticket (if needed).
