### ISSUE TITLE
Not getting sufficient filament put down.

### ISSUE THREAD

**Issue by hallambaker** [PrintM3D/Promega#22]
I am getting really bad extrusion. The filament does not seem to be coming out in sufficient quantity. I have reduced the feed rate to 30mm/sec for infill, 15mm for walls.

Seems that the issue is either a blocked nozzle or the motor isn't able to pull the filament. the spool seems to jerk a lot during printing like there is too much friction. 

I can't get anything using the PTFE tubes and so went direct.

**Comment by ericl-m3d** [comment]
Hello hallambaker,

Please log ONLY issues pertinent to software bugs or operational anomalies (suspected to be software-related).
Any other type of issues logged will be not be addressed and will be deleted.

If you are looking for support, feel free to look through our ever-improving documentation for quick help. 

- [M3D's Official Troubleshooting & Self-Help Guide](https://coda.io/d/M3D-Official-Troubleshooting-Self-Help-Guide_dzE73kMbIAL/Introduction_sucuq#_lulpw)
- [Promega Guides & Instructions](https://promega.printm3d.com/)

Our support ticket is available at https://store.printm3d.com/pages/support.

If you'd like to voice your input on improving our documentation, visit: 
- M3D's Official Troubleshooting & Self-Help Guide [Contribution & Suggestion Page](https://coda.io/d/M3D-Official-Troubleshooting-Self-Help-Guide_dzE73kMbIAL/Coda-Edits-Requests-Form_suKF6#_luq0Y)
- Promega Guides & Instructions [Contribution & Suggestion Page](https://promega.printm3d.com/#contributing)

-M3D Team

NOTE: This [sub-section](https://coda.io/d/M3D-Official-Troubleshooting-Self-Help-Guide_dzE73kMbIAL/Promega-Troubleshooting_suSw-#_lurJI) (within the Troubleshooting & Self-Help Guide) should start you off in the right direction, before submitting a support ticket (if needed).
