### ISSUE TITLE
Extrusion problem

### ISSUE THREAD

**Issue by emilalzamora** [PrintM3D/Promega#24]
Hi. I have a promega.  Started working with it in early August.  Did an update etc and have had varying degrees of success. My problem is that often the extruded seems to not be able to put out enough and so I get stringy thin went sections.  Often the print will fail because that section isn’t strong. It’s a compound nozzle. 
Please advise!! Thank you. 
Emil Alzamora

**Comment by ericl-m3d** [comment]
Hello emilalzamora,

Please log ONLY issues pertinent to software bugs or operational anomalies (suspected to be software-related).
Any other type of issues logged will be not be addressed and will be deleted.

If you are looking for support, feel free to look through our ever-improving documentation for quick help. 

- [M3D's Official Troubleshooting & Self-Help Guide](https://coda.io/d/M3D-Official-Troubleshooting-Self-Help-Guide_dzE73kMbIAL/Introduction_sucuq#_lulpw)
- [Promega Guides & Instructions](https://promega.printm3d.com/)

Our support ticket is available at https://store.printm3d.com/pages/support.

If you'd like to voice your input on improving our documentation, visit: 
- M3D's Official Troubleshooting & Self-Help Guide [Contribution & Suggestion Page](https://coda.io/d/M3D-Official-Troubleshooting-Self-Help-Guide_dzE73kMbIAL/Coda-Edits-Requests-Form_suKF6#_luq0Y)
- Promega Guides & Instructions [Contribution & Suggestion Page](https://promega.printm3d.com/#contributing)

-M3D Team

NOTE: This [sub-section](https://coda.io/d/M3D-Official-Troubleshooting-Self-Help-Guide_dzE73kMbIAL/Promega-Troubleshooting_suSw-#_lurJI) (within the Troubleshooting & Self-Help Guide) should start you off in the right direction, before submitting a support ticket (if needed).
