### ISSUE TITLE
K'Tana Print issues

### ISSUE THREAD

**Issue by caschles** [PrintM3D/Promega#25]
Team, I have installed the K'tana print head on the ProMega. The card supplied with the printer was lost and we downloaded the recent files from GitHub. The left side of the extruder works without issue. the right side heats, but will not extrude. when i look at the extruder in the Web view, everything appears to be correct.

**Comment by ericl-m3d** [comment]
Hello cashles,

Please log ONLY issues pertinent to software bugs or operational anomalies (suspected to be software-related).
Any other type of issues logged will be not be addressed and will be deleted.

If you are looking for support, feel free to look through our ever-improving documentation for quick help. 

- [M3D's Official Troubleshooting & Self-Help Guide](https://coda.io/d/M3D-Official-Troubleshooting-Self-Help-Guide_dzE73kMbIAL/Introduction_sucuq#_lulpw)
- [Promega Guides & Instructions](https://promega.printm3d.com/)

Our support ticket is available at https://store.printm3d.com/pages/support.

If you'd like to voice your input on improving our documentation, visit: 
- M3D's Official Troubleshooting & Self-Help Guide [Contribution & Suggestion Page](https://coda.io/d/M3D-Official-Troubleshooting-Self-Help-Guide_dzE73kMbIAL/Coda-Edits-Requests-Form_suKF6#_luq0Y)
- Promega Guides & Instructions [Contribution & Suggestion Page](https://promega.printm3d.com/#contributing)

-M3D Team

NOTE: This link (within Promega Guides & Instructions) may help: https://promega.printm3d.com/advanced-setup-guides/meet-the-extruder#tools
