### ISSUE TITLE
K'Tana severe Skipping

### ISSUE THREAD

**Issue by ANataleIII** [PrintM3D/Promega#26]
I am unable to get any successful prints with PLA or PETG. The skipping from the extruder is terrible. Ive made all the adjustments suggested, updated firmware, I drilled out the sleeve, but the skipping continues to grow. Now I cant even extrude the filament to purge without severe skipping and prints fail. I have tried temps from 195 to 270 depending on filament, I have tried speeds as slow as 15mm/s to 45mm/s. Ive adjusted stepper current to 550/ 550. Ive moved away from the feeder tube and run direct. Nothing is working. Link to the video is below. The fan was disconnected for the video but is normally running. the skipping is the same either way.  

https://youtu.be/eBqOyhDG8G4

**Comment by ericl-m3d** [comment]
Hello ANatalelll,

Please log ONLY issues pertinent to software bugs or operational anomalies (suspected to be software-related).
Any other type of issues logged will be not be addressed and will be deleted.

If you are looking for support, feel free to look through our ever-improving documentation for quick help. 

- [M3D's Official Troubleshooting & Self-Help Guide](https://coda.io/d/M3D-Official-Troubleshooting-Self-Help-Guide_dzE73kMbIAL/Introduction_sucuq#_lulpw)
- [Promega Guides & Instructions](https://promega.printm3d.com/)

Our support ticket is available at https://store.printm3d.com/pages/support.

If you'd like to voice your input on improving our documentation, visit: 
- M3D's Official Troubleshooting & Self-Help Guide [Contribution & Suggestion Page](https://coda.io/d/M3D-Official-Troubleshooting-Self-Help-Guide_dzE73kMbIAL/Coda-Edits-Requests-Form_suKF6#_luq0Y)
- Promega Guides & Instructions [Contribution & Suggestion Page](https://promega.printm3d.com/#contributing)

-M3D Team

NOTE: The troubleshooting guide should be able to set you in the right direction, before sending a ticket (if needed).
