### ISSUE TITLE
Pro mega Network Setup

### ISSUE THREAD

**Issue by WilliamLalum** [PrintM3D/Promega#27]
We are unable to get either of our laptops to connect to the pro mega.  We have changed none of the default settings on the sd card. 
We have an Ethernet cable attached to the printer to our router.  Lights come on as instructed.  Power is on to the duet board.  When we open a browser in chrome with the address of promega/ we get a IP address cannot be found. Any advice?

**Comment by swblum** [comment]
By default the Promega is set up for DHCP so your router should assign it an address. You can look in your router interface to discern what the IP Address is of the printer. If you have already done the above I would recommend setting a static IP in the config.g if you have the factory SD card structure.

**Comment by TheBum** [comment]
The instructions assume that your router has a built-in LAN DNS for devices that use DHCP to get their IP addresses. It's a bad assumption because most low cost routers don't.

**Comment by WilliamLalum** [comment]
Ok. We found the IP address the router is assigning to the printer. Should we set the M552 command to that address on the SD card?

**Comment by sohjsolwin** [comment]
> The instructions assume that your router has a built-in LAN DNS for devices that use DHCP to get their IP addresses. It's a bad assumption because most low cost routers don't.

I disagree with that statement. Every _router_ I've ever owned, even the cheap ones, have assigned IP addressed to devices connected to them. _switches_ on the other hand, just pass the connection along and do not assign IPs. 

> Ok. We found the IP address the router is assigning to the printer. Should we set the M552 command to that address on the SD card?

No, you do not need to set the IP in the SD card, unless you want to use a static IP. If that is the case, you should also make it static on your router so that on a renew it does not potentially assign that same IP to something else on your network first. If you do not assign a static IP, you should be able to access the printer from http://promega/ regardless of which IP the router ends up assigning to it.

**Comment by TheBum** [comment]
I’m referring to the instructions that say to type “promega” into the address field in the browser. That doesn’t work on most home routers.

**Comment by ericl-m3d** [comment]
Please log ONLY issues pertinent to software bugs or operational anomalies (suspected to be software-related). Any other type of issues logged will be not be addressed and will be deleted.

If you are looking for support, feel free to look through our ever-improving documentation for quick help.

- https://coda.io/d/M3D-Official-Troubleshooting-Self-Help-Guide_dzE73kMbIAL/Introduction_sucuq#_lulpw
- https://promega.printm3d.com/

Our support ticket is available at https://store.printm3d.com/pages/support.

-M3D Team

NOTE: This link should help: https://promega.printm3d.com/getting-started/setup-your-network#configuring-network-settings. 

Thank you for your comments. We will take another look at our network guide for potential clarifications. 
If you'd like, you can voice your input at https://promega.printm3d.com/#contributing.
