### ISSUE TITLE
Promega networking dead

### ISSUE THREAD

**Issue by mtkgrafix** [PrintM3D/Promega#28]
Just received my Promega and have tried the default SD card config with no success.

The network activity lights never show any activity (or light). I have tried multiple ETH cables (new and tested on other equipment). Tried multiple ports on the switch (also confirmed working with other equipment).

I then tried to assign a static address but that didn't help (I have the second SD card so edited that one). I've also downloaded a new SD structure for my K'tana config and nothing changed.

I have never inserted/removed the SD card with the power on. The three LEDs on the Duet board itself do light up but never see even a flash on the ETH port activity lights. It never asks my DHCP server for an IP (checked logs).

When I plug in the USB cable for the Duet the Parallels VM on my Mac does recognize the device as a 'Duet' but I'm not able to mount the SD card (either card, original or modified).

Both SD cards work just fine when inserted in the little USB converter provided. That is how I was able to edit the second card provided to try a static address.

I'm afraid the SD port is bad or there is a problem with the ETH port itself.

The Promega did arrive in good shape. I opted for the wooden crate 'just in case' packaging and the cardboard outside of that wooden crate even looked like it'd had an uneventful trip.

This image show's the only LEDs that light up when the Duet is powered up. They light up like this on the Duet and stay that way (never any on the ETH port):

![img_2274](https://user-images.githubusercontent.com/392838/46965124-93895b80-d06f-11e8-8a00-dcdc988875c8.jpg)

**Comment by bass4aj** [comment]
Hey, log a support ticket on their site. I had a board with that issue too and had it replaced under warranty.

**Comment by mtkgrafix** [comment]
> Hey, log a support ticket on their site. I had a board with that issue too and had it replaced under warranty.

Thanks bass4aj - I just got my instructions to ship the board back.  👍🏻
