### ISSUE TITLE
What is being done to fix the bed level switch so that the solder joints don't break?

### ISSUE THREAD

**Issue by daniel-farina** [PrintM3D/Promega#3]
This is a new issue.  Since limit switches we intended to be stationary, it seems they're being cycled beyond their design.  The initial limit switches we made were a stand in for the ones were making in the long term.  We'll reduce stress at the interface in those and the new design is also a deployable slide switch.

UPDATE 07-07-2018  Limit switches issues have been pushed to the manufacturers, who is making new ones that are soldered better;  The print file that holds them in place will then lock in the wires to eliminate bending stresses on that joint.

⚠️ _This question was originally posted on Airtable. It has been moved to Github for better trackability_

**Comment by michaelarmani** [comment]
No further breaks have been reported.
