### ISSUE TITLE
EXtruders Nozzels at 2 different levels - plus bed slipping?

### ISSUE THREAD

**Issue by jackmartintx** [PrintM3D/Promega#31]
1.  The Promega arrived with all 4 Z sliders broken.
2.  It was a nightmare trying to figure out how to redo and twist, etc.
3.  After multiple alignment and mapping attempts, I think the issue is the bed is slipping or skipping.  Z0 seems to be "moving".  What would cause this?
4.  While attempting yet another alignment and leveling I realize that now my nozzles are at two different levels.
5.  I have put close to 100 hours into the Promega and yet to print anything.

Ideas?

**Comment by ericl-m3d** [comment]
Please log ONLY issues pertinent to software bugs or operational anomalies (suspected to be software-related)
Any other type of issues logged will be not be addressed and will be deleted.

If you are looking for support, feel free to look through our ever-improving documentation for quick help. 

- https://coda.io/d/M3D-Official-Troubleshooting-Self-Help-Guide_dzE73kMbIAL/Introduction_sucuq#_lulpw
- https://promega.printm3d.com/

Our support ticket is available at https://store.printm3d.com/pages/support 

-M3D Team
