### ISSUE TITLE
Extruder Skips Then Stops

### ISSUE THREAD

**Issue by DesignSteinStudios** [PrintM3D/Promega#32]
I have tried using the Compound and Single K'Tana head and also ABS and PLA and I am having the same issue with the right side extruder. Everything works fine for the fist 200-300mm of a print then I can start the hear the right gear that pulls the filament into the extruder start to skip. Shortly after the gear spins so many times it carves a groove in the filament and it won't extruded anymore and I have to cancel the print.

I have taken apart the head multiple times and there are no obstructions, just the gear that has filament shavings on it and a stuck filament.

I have adjusted the nozzle temperature and feed rate and the same problem still happens. Under machine control I extrude 100mm at 5mm/sec and the first 2 rounds goes well. Then by the 3rd round it starts to skip and gets stuck. If I try to extrude at anything faster than 5mm/sec it skips constantly.

I checked my e-motor steps and there were at E1560:1532:420:420 so I typed the G code M92 E195:191.5 in and it seems to fix the readout issue but the same problem still happens.

Any ideas?

**Comment by DesignSteinStudios** [comment]
So you don’t even bother to answer my question and you close it out? Your printer is a piece of fucking shit and so is your support. I will do everything possible to notify the design and maker community how horrible your printers are. I’ve already convinced 10 people from github to not purchase the Promega.



Jesse Clemmer
PRESIDENT
O – 714.375.4846 C – 949.275.4554
7602 Talbert #D, Huntington Beach, CA 92648
www.DesignSteinStudios.com<http://designsteinstudios.com/>
[logo_signature]




Confidentiality: The information contained in this e-mail transmission is intended only for the use of the individual or entity named above. This e-mail transmission, and any documents, files, previous e-mail transmissions or other information attached to it, may contain confidential information that is legally privileged. If you are not the intended recipient of this e-mail message, or the employee or agent responsible for delivering it to the intended recipient, you are hereby notified that any disclosure, dissemination, distribution, copying or other use of this transmission or any of the information contained in or attached to it is strictly prohibited. If you have received this e-mail transmission in error, please immediately notify us by return e-mail transmission or by telephone at (949) 275-4554, and destroy the original e-mail transmission and its attachments without reading, saving, or utilizing it in any manner.

**Comment by ericl-m3d** [comment]
We understand your frustration with the delay and are doing our best to help, however we cannot tolerate profanity in our channels of communication. Please keep the language professional or we will have to stop this interaction. 

ONLY logged issues pertinent to software bugs or operational anomalies (suspected to be software-related)
Any other type of issues logged will be not be addressed and will be deleted.

If you are looking for support, feel free to look through our ever-improving documentation for quick help. 

- https://coda.io/d/M3D-Official-Troubleshooting-Self-Help-Guide_dzE73kMbIAL/Introduction_sucuq#_lulpw
- https://promega.printm3d.com/

Our support ticket is available at https://store.printm3d.com/pages/support 

-M3D Team

**Comment by DesignSteinStudios** [comment]
Horrible product, horrible design, horrible rip off. I will spread the word



Jesse Clemmer
PRESIDENT
O – 714.375.4846 C – 949.275.4554
7602 Talbert #D, Huntington Beach, CA 92648
www.DesignSteinStudios.com<http://designsteinstudios.com/>
[logo_signature]




Confidentiality: The information contained in this e-mail transmission is intended only for the use of the individual or entity named above. This e-mail transmission, and any documents, files, previous e-mail transmissions or other information attached to it, may contain confidential information that is legally privileged. If you are not the intended recipient of this e-mail message, or the employee or agent responsible for delivering it to the intended recipient, you are hereby notified that any disclosure, dissemination, distribution, copying or other use of this transmission or any of the information contained in or attached to it is strictly prohibited. If you have received this e-mail transmission in error, please immediately notify us by return e-mail transmission or by telephone at (949) 275-4554, and destroy the original e-mail transmission and its attachments without reading, saving, or utilizing it in any manner.
