### ISSUE TITLE
Print Cooling Fans Popped and Smoked

### ISSUE THREAD

**Issue by talonzme** [PrintM3D/Promega#33]
Anyone know the specs on the print cooling fans (2 little ones inside shroud)?  I was running a print yesterday and they popped then started smoking (badly).  I had to unplug them.  They won't run now,obviously, so I will need to replace them.  Not sure is the printer warranty is still in effect or not.  No changing of wires was done since the voltages are different between these and the nozzle fan.  I cannot find specs to replace the two print cooling fans though.

**Comment by TheBum** [comment]
Since both blew out at the same time, I would suspect the Maestro board. In any case, it absolutely should be covered by the warranty.

**Comment by talonzme** [comment]
How do I start the process to get them replaced? I am not seeing any other place to submit an issue but here....

**Comment by jbolene** [comment]
https://store.printm3d.com/pages/support

**Comment by talonzme** [comment]
Thank you jbolene. I realized I didn't have an account for that page. I have submitted the "chat" to request the fans.
