### ISSUE TITLE
Duet Web Control is Outdated

### ISSUE THREAD

**Issue by fallsimply** [PrintM3D/Promega#56]
Duet Web Control 2 came out October 1st.

All you would have to do is update the www directory in the firmware

Repository: https://github.com/chrishamm/DuetWebControl/
Release: https://github.com/chrishamm/DuetWebControl/releases

**Comment by michaelarmani** [comment]
We do appreciate the pointer and others who can find it will hopefully understand the risks and benefits of making changes.  For our first time users we use a "don't fix unless broken" approach with our versions.  Standardizing to the last best known release keeps everyone on the same page as far as resetting and troubleshooting. There have been quite a number of problems for example with users updated to the Duet 3 firmware base as it has yet to be stable.  We'll keep evaluating versions on a continuous basis.
