### ISSUE TITLE
github changes

### ISSUE THREAD

**Issue by jbolene** [PrintM3D/Promega#9]
I changed the screws and tools 2 weeks ago and my changes have not appeared.
You want us to help and when we do, it seems nothing changes.

**Comment by sohjsolwin** [comment]
Upon digging in, we found that you had actually closed the PR instead of leaving it open to be merged in. That is why your changes 2 weeks ago didn't go anywhere. After figuring that out and speaking with you, you managed to open the PR back up so that M3D can review and merge it in.
